site_name: Tree
site_description: Tree

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/images/favicon.png
  language: en
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings

nav:
  - Overview: index.md
  - Reference: reference/

extra_css:
- assets/css/code_select.css

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.highlight:
    use_pygments: true
    pygments_lang_class: true
- attr_list
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.tasklist:
    custom_checkbox: true

copyright: Copyright &copy; 2022 Hong Ji

extra:
  generator: false
